import pytest
from unittest.mock import patch, MagicMock
from datetime import datetime, timezone, timedelta
from license_server.routes import send_email
from license_server.config import settings


def test_send_email_error_catch(capsys):
    """Test that send_email catches and prints exceptions instead of crashing."""
    with patch("license_server.routes.settings") as mock_settings:
        mock_settings.RESEND_API_KEY = "dummy-key"
        mock_settings.RESEND_FROM_EMAIL = "from@ex.com"
        
        with patch("resend.Emails.send", side_effect=Exception("API Down")):
            send_email("to@ex.com", "Subject", "Body")
            
    captured = capsys.readouterr()
    assert "Failed to send email: API Down" in captured.out

@pytest.mark.asyncio
async def test_verify_email_invalid_token(client):
    """Test 404 for invalid verification token."""
    resp = await client.get("/verify-email?token=non-existent-token")
    assert resp.status_code == 404
    assert "Invalid or expired verification token" in resp.json()["detail"]

@pytest.mark.asyncio
async def test_verify_email_expired_token(client, session, target_app_id):
    """Test 400 for expired verification token."""
    from license_server.models import VerificationRequest
    
    # Create an expired request
    expires_at = datetime.now(timezone.utc) - timedelta(hours=1)
    req = VerificationRequest(
        email="expired@ex.com",
        app_id=target_app_id,
        token="expired-token",
        expires_at=expires_at
    )
    session.add(req)
    await session.commit()
    
    resp = await client.get("/verify-email?token=expired-token")
    assert resp.status_code == 400
    assert "Verification token has expired" in resp.json()["detail"]

@pytest.mark.asyncio
async def test_validate_license_expired(client, session, target_app_id, auth_headers):
    """Test 403 for expired but not revoked license."""
    from license_server.models import License
    
    expires_at = datetime.now(timezone.utc) - timedelta(days=1)
    req = License(
        email="user@ex.com",
        app_id=target_app_id,
        tier="community",
        license_key="expired-key",
        expires_at=expires_at
    )
    session.add(req)
    await session.commit()
    
    resp = await client.post("/validate-license?license_key=expired-key", headers=auth_headers)
    assert resp.status_code == 403
    assert "License expired" in resp.json()["detail"]

@pytest.mark.asyncio
async def test_get_public_key_missing(temp_keys_dir):
    """Test get_public_key when file is missing."""
    import os
    from license_server.routes import get_public_key
    from license_server.config import settings
    
    # remove public key if it was generated by some other test side-effect
    if os.path.exists(settings.PUBLIC_KEY_PATH):
        os.remove(settings.PUBLIC_KEY_PATH)
        
    assert "Public key file not found" in get_public_key()
